version: "3.9"

services:

 nginx:
  image: nginx:latest
  ports:
   - "80:80"
  volumes:
   - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
   - ./docker/nginx/conf:/etc/nginx/conf.d
   - ./www:/var/www/

 php-fpm:
  build: ./docker/php/php-fpm
  volumes:
   - ./www:/var/www/

 db:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - 3306:3306
  volumes:
   - ./docker/dbdata:/var/lib/mysql
   - ./docker/dbdump:/var/local
  environment:
   MYSQL_ROOT_PASSWORD: dbroot
   MYSQL_DATABASE: testdb
   MYSQL_USER: testuser
   MYSQL_PASSWORD: testuser

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin:latest
  restart: always
  ports:
   - "3000:80"
  environment:
   PMA_HOST: db
   MYSQL_ROOT_PASSWORD: dbroot
   PMA_USER: testuser
   PMA_PASSWORD: testuser


    # cli:
    #   build: ./docker/php/php-cli
    #   volumes:
    #     - ./www:/var/www    
